# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo hello world1
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: repo git
          version: 1.0


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p /home/runner/msmnile_au_aosp
          cd /home/runner/msmnile_au_aosp
          repo init --depth 1 -u https://git.codelinaro.org/clo/la/platform/manifest.git -b release -m LA.AU.1.4.5.r1-02800-gen3meta.0.xml --repo-url=https://git.codelinaro.org/clo/tools/repo.git --repo-branch=aosp/stable
          repo sync --fail-fast -j4 platform/vendor/opensource/video-driver platform/vendor/opensource/camera-kernel platform/vendor/opensource/audio-kernel platform/vendor/opensource/display-drivers platform/vendor/opensource/dataipa platform/vendor/opensource/video-driver kernel/msm-5.4
          
